#!/usr/bin/env bash
# User-mode FRTB deploy: process-only, verbose-by-default. Wave 5.76.
set -euo pipefail
shopt -s nullglob

REPO="$(cd "$(dirname "$0")/.." && pwd)"
STATE_DIR="$REPO/.frtb"
ENV_FILE="$STATE_DIR/env"
LOG_DIR="$STATE_DIR/logs"
RUN_DIR="$STATE_DIR/run"
STATE_FILE="$STATE_DIR/state.json"

SERVICES=(api calc source ingest generator loadgen)

svc_port() {
  case "$1" in
    api)       echo 8080 ;;
    calc)      echo 3000 ;;
    source)    echo 8082 ;;
    ingest)    echo 8083 ;;
    loadgen)   echo 8085 ;;
    generator) echo "-" ;;
    *)         echo "-" ;;
  esac
}

if [ -t 1 ]; then
  C_OK=$'\033[32m'; C_WARN=$'\033[33m'; C_ERR=$'\033[31m'; C_DIM=$'\033[2m'; C_RST=$'\033[0m'
else
  C_OK=""; C_WARN=""; C_ERR=""; C_DIM=""; C_RST=""
fi
ok()   { printf '%s✓%s %s\n'  "$C_OK"   "$C_RST" "$*"; }
warn() { printf '%s!%s %s\n'  "$C_WARN" "$C_RST" "$*" >&2; }
err()  { printf '%s✗%s %s\n'  "$C_ERR"  "$C_RST" "$*" >&2; }
dim()  { printf '%s%s%s\n'    "$C_DIM"  "$*"    "$C_RST"; }

usage() {
  cat <<'EOF'
Usage: scripts/deploy.sh <command> [args]

Commands:
  install --redis-url <URL> [--verbose]   Install: create .frtb/, env, pnpm install + build
  start [svc]                             Start all services, or one (api|calc|source|ingest|generator|loadgen)
  stop [svc]                              Stop all services, or one
  restart [svc]                           Stop then start
  status                                  Print one-line-per-service status table
  logs <svc> [-f|--follow]                Print or follow the service log

All runtime state lives in <repo>/.frtb/ (env, logs/, run/, state.json).
Runs as the invoking user. No sudo, no service account, no systemd.
To reset cleanly: stop all, then `rm -rf .frtb/`.
EOF
}

is_known_svc() {
  local s="$1"
  for k in "${SERVICES[@]}"; do [ "$k" = "$s" ] && return 0; done
  return 1
}

ensure_installed() {
  [ -f "$ENV_FILE" ] || { err "not installed (no $ENV_FILE). Run: scripts/deploy.sh install --redis-url <URL>"; exit 1; }
}

load_env() {
  ensure_installed
  set -a
  # shellcheck disable=SC1090
  . "$ENV_FILE"
  set +a
}

pid_alive() {
  local pid="$1"
  [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null
}

read_pid() {
  local f="$1"
  [ -f "$f" ] && cat "$f" 2>/dev/null || true
}

mask_url() {
  # rediss://:secret@host:port -> rediss://:***@host:port
  local u="$1"
  printf '%s' "$u" | sed -E 's#(://[^:/@]*:)[^@]+@#\1***@#'
}

cmd_install() {
  local redis_url="" verbose=0
  while [ $# -gt 0 ]; do
    case "$1" in
      --redis-url) redis_url="${2:-}"; shift 2 ;;
      --verbose|-v) verbose=1; shift ;;
      -h|--help) usage; exit 0 ;;
      *) err "unknown install arg: $1"; exit 1 ;;
    esac
  done
  if [ -z "$redis_url" ]; then
    err "install requires --redis-url <URL>"
    exit 1
  fi

  mkdir -p "$LOG_DIR" "$RUN_DIR"

  if [ -f "$ENV_FILE" ]; then
    warn "env exists, keeping; delete $ENV_FILE to regenerate"
  else
    local master conn token
    master=$(openssl rand -hex 32)
    conn=$(openssl rand -hex 32)
    token=$(openssl rand -hex 16)
    umask 077
    cat > "$ENV_FILE" <<EOF
# Generated by scripts/deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
REDIS_URL=$redis_url
FRTB_MASTER_KEY=$master
CONN_STORE_KEY=$conn
INTERNAL_API_TOKEN=$token
LOG_LEVEL=debug
NODE_ENV=development
FRTB_REPO=$REPO
EOF
    chmod 600 "$ENV_FILE"
    umask 022
    ok "wrote $ENV_FILE (mode 0600)"
  fi

  ( cd "$REPO" && pnpm install ) || { err "pnpm install failed"; exit 1; }
  ( cd "$REPO" && pnpm -r build ) || { err "pnpm -r build failed"; exit 1; }

  cat > "$STATE_FILE" <<EOF
{
  "installed_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "redis_url_masked": "$(mask_url "$redis_url")",
  "repo_path": "$REPO"
}
EOF
  ok "wrote $STATE_FILE"
  echo
  dim "Next steps:"
  dim "  scripts/deploy.sh start"
  dim "  scripts/deploy.sh status"
  dim "  scripts/deploy.sh logs api -f"
}

start_one() {
  local svc="$1"
  if ! is_known_svc "$svc"; then err "unknown service: $svc"; exit 1; fi
  local pidfile="$RUN_DIR/$svc.pid"
  local logfile="$LOG_DIR/$svc.log"
  local existing
  existing=$(read_pid "$pidfile")
  if pid_alive "$existing"; then
    warn "$svc already running (pid $existing)"
    return 0
  fi
  rm -f "$pidfile"
  mkdir -p "$LOG_DIR" "$RUN_DIR"
  cd "$REPO"
  local pid
  if command -v setsid >/dev/null 2>&1; then
    nohup setsid pnpm --filter "@frtb/$svc" start >> "$logfile" 2>&1 < /dev/null &
    pid=$!
  else
    nohup pnpm --filter "@frtb/$svc" start >> "$logfile" 2>&1 < /dev/null &
    pid=$!
  fi
  echo "$pid" > "$pidfile"
  sleep 1
  if ! pid_alive "$pid"; then
    err "$svc failed to start; last 20 log lines:"
    tail -n 20 "$logfile" >&2 || true
    rm -f "$pidfile"
    exit 1
  fi
  ok "$svc started (pid $pid) → $logfile"
}

cmd_start() {
  load_env
  if [ $# -eq 0 ]; then
    for s in "${SERVICES[@]}"; do start_one "$s"; done
  else
    start_one "$1"
  fi
}

stop_one() {
  local svc="$1"
  if ! is_known_svc "$svc"; then err "unknown service: $svc"; exit 1; fi
  local pidfile="$RUN_DIR/$svc.pid"
  local pid
  pid=$(read_pid "$pidfile")
  if ! pid_alive "$pid"; then
    dim "$svc not running"
    rm -f "$pidfile"
    return 0
  fi
  kill -TERM "$pid" 2>/dev/null || true
  local i=0
  while [ $i -lt 10 ] && pid_alive "$pid"; do
    sleep 1
    i=$((i+1))
  done
  if pid_alive "$pid"; then
    warn "$svc still alive after 10s, sending SIGKILL"
    kill -KILL "$pid" 2>/dev/null || true
    sleep 1
  fi
  rm -f "$pidfile"
  ok "$svc stopped (was pid $pid)"
}

cmd_stop() {
  if [ $# -eq 0 ]; then
    for s in "${SERVICES[@]}"; do stop_one "$s"; done
  else
    stop_one "$1"
  fi
}

cmd_restart() {
  cmd_stop "$@"
  cmd_start "$@"
}

human_size() {
  local f="$1"
  [ -f "$f" ] || { echo "0 B"; return; }
  local b
  if stat -f%z "$f" >/dev/null 2>&1; then
    b=$(stat -f%z "$f")
  else
    b=$(stat -c%s "$f" 2>/dev/null || echo 0)
  fi
  if [ "$b" -lt 1024 ]; then echo "${b} B"
  elif [ "$b" -lt 1048576 ]; then echo "$((b/1024)) KB"
  else echo "$((b/1048576)) MB"; fi
}

cmd_status() {
  printf '%-11s %-7s %-9s %-7s %-12s %s\n' SERVICE PID RUNNING PORT "LOG SIZE" "LAST LINE"
  for svc in "${SERVICES[@]}"; do
    local pidfile="$RUN_DIR/$svc.pid"
    local logfile="$LOG_DIR/$svc.log"
    local pid running port size last
    pid=$(read_pid "$pidfile")
    if pid_alive "$pid"; then
      running="yes"
    else
      running="no"
      pid="—"
    fi
    port=$(svc_port "$svc")
    [ "$running" = "no" ] && port="—"
    size=$(human_size "$logfile")
    if [ -f "$logfile" ] && [ -s "$logfile" ]; then
      last=$(tail -n 1 "$logfile" 2>/dev/null | tr -d '\r' | cut -c1-80)
    else
      last="—"
    fi
    printf '%-11s %-7s %-9s %-7s %-12s %s\n' "$svc" "$pid" "$running" "$port" "$size" "$last"
  done
}

cmd_logs() {
  local svc="${1:-}" follow=0
  if [ -z "$svc" ]; then err "logs requires a service name"; exit 1; fi
  if ! is_known_svc "$svc"; then err "unknown service: $svc"; exit 1; fi
  shift || true
  case "${1:-}" in
    -f|--follow) follow=1 ;;
    "") ;;
    *) err "unknown logs arg: $1"; exit 1 ;;
  esac
  local logfile="$LOG_DIR/$svc.log"
  if [ ! -f "$logfile" ]; then
    echo "no log yet — has \`$svc\` been started?"
    return 0
  fi
  if [ "$follow" -eq 1 ]; then
    tail -F "$logfile"
  else
    tail -n 200 "$logfile"
  fi
}

main() {
  local cmd="${1:-}"
  [ $# -gt 0 ] && shift || true
  case "$cmd" in
    install)            cmd_install "$@" ;;
    start)              cmd_start "$@" ;;
    stop)               cmd_stop "$@" ;;
    restart)            cmd_restart "$@" ;;
    status)             cmd_status "$@" ;;
    logs)               cmd_logs "$@" ;;
    -h|--help|help|"")  usage ;;
    *) err "unknown command: $cmd"; usage; exit 1 ;;
  esac
}

main "$@"
